/*5 - Lista de los 5 condados (FIPS_NAME) con mayor cantidad de incendios registrados*/

CREATE VIEW TOP_5_CONDADOS_CON_MAYOR_CANTIDAD_DE_INCENDIOS_REGISTRADOS AS
SELECT FIPS_NAME AS NOMBRE_CONDADO, COUNT(*) AS Nº_INCENDIOS
FROM FIRES WHERE NOMBRE_CONDADO IS NOT NULL
GROUP BY NOMBRE_CONDADO
ORDER BY Nº_INCENDIOS DESC 
LIMIT 5;